#!/usr/bin/env python3
"""
IPCon v.1 - DNS Protection
"""

import asyncio
import logging
from typing import List, Optional
from pathlib import Path

logger = logging.getLogger(__name__)


class DNSProtection:
    """DNS leak protection"""
    
    DEFAULT_DNS = ["1.1.1.1", "1.0.0.1"]
    
    def __init__(self, dns_servers: Optional[List[str]] = None):
        self.dns_servers = dns_servers or self.DEFAULT_DNS
        self._enabled = False
        self._original_resolv_conf: Optional[str] = None
        self._lock = asyncio.Lock()
    
    async def enable(self) -> bool:
        """Enable DNS leak protection."""
        async with self._lock:
            if self._enabled:
                logger.info("DNS protection already enabled")
                return True
            
            try:
                logger.info("Enabling DNS leak protection...")
                
                resolv_path = Path("/etc/resolv.conf")
                
                if resolv_path.exists():
                    self._original_resolv_conf = resolv_path.read_text()
                
                content = "# Generated by IPCon DNS Protection\n"
                for dns in self.dns_servers:
                    content += f"nameserver {dns}\n"
                
                resolv_path.write_text(content)
                resolv_path.chmod(0o644)
                
                self._enabled = True
                logger.info(f"DNS protection enabled - Using {self.dns_servers}")
                return True
                
            except PermissionError:
                logger.error("Permission denied - Run as root")
                return False
            except Exception as e:
                logger.error(f"Failed to enable DNS protection: {e}")
                return False
    
    async def disable(self) -> bool:
        """Disable DNS leak protection."""
        async with self._lock:
            if not self._enabled:
                return True
            
            try:
                logger.info("Disabling DNS protection...")
                
                if self._original_resolv_conf:
                    Path("/etc/resolv.conf").write_text(self._original_resolv_conf)
                
                self._enabled = False
                logger.info("DNS protection disabled")
                return True
                
            except Exception as e:
                logger.error(f"Failed to disable DNS protection: {e}")
                return False
    
    async def is_enabled(self) -> bool:
        """Check if DNS protection is enabled."""
        return self._enabled
